name: Build Design Tokens

on:
  push:
    paths:
      - 'input/tokens.json'
      - 'build.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the latest LTS version

      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: node build.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<your-email>"
          git add -A
          git commit -m "Automatically built design tokens" || echo "No changes to commit"
          git push
